apiVersion: v1
kind: Service
metadata:
  name: flask-app-service
spec:
  selector:
    app: flask-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer  # Use "LoadBalancer" if you are working in a cloud environment, else use "NodePort" or "ClusterIP" depending on your setup
